apiVersion: apps/v1
kind: Deployment
metadata:
  name: botzin
  annotations:
    argocd-image-updater.argoproj.io/image-list: ghcr.io/yutzinvr/botzin:latest
    argocd-image-updater.argoproj.io/update-strategy: digest
    argocd-image-updater.argoproj.io/write-back-method: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: botzin
  template:
    metadata:
      labels:
        app: botzin
    spec:
      containers:
      - name: botzin
        image: ghcr.io/yutzinvr/botzin:latest
        imagePullPolicy: Always
        env:
        - name: DISCORD_TOKEN
          valueFrom:
            secretKeyRef:
              name: botzin
              key: DISCORD_TOKEN
