apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: valheim
spec:
  project: default
  sources:
  - repoURL: 'https://addyvan.github.io/valheim-k8s/'
    chart: valheim-k8s
    targetRevision: 1.2.0
    helm:
      values: |
        worldName: Treehouse
        serverName: Treehouse
        passwordSecret: valheim
        storage:
          kind: persistentVolumeClaim
          pvc:
            storageClassName: local-storage
            size: 20Gi
        serverStorage:
          kind: persistentVolumeClaim
          pvc:
            storageClassName: local-storage
            size: 20Gi
        networking:
          serviceType: NodePort
          nodePort: 2456
        extraEnvironmentVars:
          BEPINEX: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
