apiVersion: endpointmonitor.stakater.com/v1alpha1
kind: EndpointMonitor
metadata:
  name: jellyfin
spec:
  forceHttps: true
  urlFrom:
    ingressRef:
      name: jellyfin
  updownConfig:
    enable: true
    period: 3600
    publishPage: true
