apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: factorio
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage
  volumeName: factorio
