apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
spec:
  project: default
  sources:
  - repoURL: 'https://charts.longhorn.io'
    chart: longhorn
    targetRevision: 1.7.1
    helm:
      values: |
        preUpgradeChecker:
          jobEnabled: false
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: longhorn-system
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
