apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
spec:
  project: default
  sources:
  - repoURL: 'https://github.com/longhorn/charts.git'
    chart: longhorn
    targetRevision: 1.7.1
  destination:
    namespace: longhorn-system
