apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
        - name: minecraft
          image: marctv/minecraft-papermc-server:1.20.1
          ports:
            - containerPort: 25565
          env:
            - name: MEMORYSIZE
              value: "2G"
          volumeMounts:
            - mountPath: /data
              name: minecraft
          stdin: true
          tty: true
      volumes:
        - name: minecraft
          persistentVolumeClaim:
            claimName: minecraft
