apiVersion: v1
kind: Service
metadata:
  name: minecraft
spec:
  type: NodePort
  selector:
    app: minecraft  # This should match the label of your Minecraft pod
  ports:
    - protocol: TCP
      port: 25565  # Minecraft default port
      targetPort: 25565  # Port on the container
      nodePort: 25565
