apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
spec:
  project: default
  sources:
  - repoURL: 'https://kubernetes.github.io/ingress-nginx'
    chart: ingress-nginx
    targetRevision: 4.11.2
    helm:
      values: |
        controller:
          service:
            externalTrafficPolicy: Local
            type: NodePort
            nodePorts:
              http: 80
              https: 443
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ingress-nginx
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
